name: automated tests for pull requests
on:
  pull_request:
    branches: [develop]
jobs:
  test_mobile:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: happy_mucher_frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up flutter
        uses: subosito/flutter-action@v2.4.0

      - name: install dependencies
        run: flutter pub get

      - name: verify code formatting
        if: always()
        run: flutter format --output=none --set-exit-if-changed .

      - name: check for warnings
        if: always()
        run: flutter analyze

      - name: run tests
        if: always()
        run: flutter test

      - name: run integration tests
        if: always()
        run: flutter drive --target=test_driver/app.dart
